<?php
function ChIDToName($name){
    switch($name){
    case "Aatro"X: return 266; break;
    case "Thresh": return 412; break;
    case "Tryndamere": return 23; break;
    case "Gragas": return 79; break;
    case "Cassiopeia": return 69; break;
    case "Aurelion Sol": return 136; break;
    case "Ryze": return 13; break;
    case "Poppy": return 78; break;
    case "Sion": return 14; break;
    case "Annie": return 1; break;
    case "Jhin": return 202; break;
    case "Karma": return 43; break;
    case "Nautilus": return 111; break;
    case "Kled": return 240; break;
    case "Lu"X: return 99; break;
    case "Ahri": return 103; break;
    case "Olaf": return 2; break;
    case "Viktor": return 112; break;
    case "Anivia": return 34; break;
    case "Singed": return 27; break;
    case "Garen": return 86; break;
    case "Lissandra": return 127; break;
    case "Maokai": return 57; break;
    case "Morgana": return 25; break;
    case "Evelynn": return 28; break;
    case "Fizz": return 105; break;
    case "Heimerdinger": return 74; break;
    case "Zed": return 238; break;
    case "Rumble": return 68; break;
    case "Mordekaiser": return 82; break;
    case "Sona": return 37; break;
    case "Kog'Maw": return 96; break;
    case "Katarina": return 55; break;
    case "Lulu": return 117; break;
    case "Ashe": return 22; break;
    case "Karthus": return 30; break;
    case "Alistar": return 12; break;
    case "Darius": return 122; break;
    case "Vayne": return 67; break;
    case "Varus": return 110; break;
    case "Udyr": return 77; break;
    case "Leona": return 89; break;
    case "Jayce": return 126; break;
    case "Syndra": return 134; break;
    case "Pantheon": return 80; break;
    case "Riven": return 92; break;
    case "Kha'Zi"X: return 121; break;
    case "Corki": return 42; break;
    case "Azir": return 268; break;
    case "Caitlyn": return 51; break;
    case "Nidalee": return 76; break;
    case "Kennen": return 85; break;
    case "Galio": return 3; break;
    case "Veigar": return 45; break;
    case "Bard": return 432; break;
    case "Gnar": return 150; break;
    case "Malzahar": return 90; break;
    case "Graves": return 104; break;
    case "Vi": return 254; break;
    case "Kayle": return 10; break;
    case "Irelia": return 39; break;
    case "Lee Sin": return 64; break;
    case "Illaoi": return 420; break;
    case "Elise": return 60; break;
    case "Volibear": return 106; break;
    case "Nunu": return 20; break;
    case "Twisted Fate": return 4; break;
    case "Jax": return 24; break;
    case "Shyvana": return 102; break;
    case "Kalista": return 429; break;
    case "Dr. Mundo": return 36; break;
    case "Ivern": return 427; break;
    case "Diana": return 131; break;
    case "Tahm Kench": return 223; break;
    case "Brand": return 63; break;
    case "Sejuani": return 113; break;
    case "Vladimir": return 8; break;
    case "Zac": return 154; break;
    case "Rek'Sai": return 421; break;
    case "Quinn": return 133; break;
    case "Akali": return 84; break;
    case "Taliyah": return 163; break;
    case "Tristana": return 18; break;
    case "Hecarim": return 120; break;
    case "Sivir": return 15; break;
    case "Lucian": return 236; break;
    case "Rengar": return 107; break;
    case "Warwick": return 19; break;
    case "Skarner": return 72; break;
    case "Malphite": return 54; break;
    case "Yasuo": return 157; break;
    case "Xerath": return 101; break;
    case "Teemo": return 17; break;
    case "Nasus": return 75; break;
    case "Renekton": return 58; break;
    case "Draven": return 119; break;
    case "Shaco": return 35; break;
    case "Swain": return 50; break;
    case "Talon": return 91; break;
    case "Janna": return 40; break;
    case "Ziggs": return 115; break;
    case "Ekko": return 245; break;
    case "Orianna": return 61; break;
    case "Fiora": return 114; break;
    case "Fiddlesticks": return 9; break;
    case "Cho'Gath": return 31; break;
    case "Rammus": return 33; break;
    case "LeBlanc": return 7; break;
    case "Soraka": return 16; break;
    case "Zilean": return 26; break;
    case "Nocturne": return 56; break;
    case "Jin"X: return 222; break;
    case "Yorick": return 83; break;
    case "Urgot": return 6; break;
    case "Kindred": return 203; break;
    case "Miss Fortune": return 21; break;
    case "Wukong": return 62; break;
    case "Blitzcrank": return 53; break;
    case "Shen": return 98; break;
    case "Braum": return 201; break;
    case "Xin Zhao": return 5; break;
    case "Twitch": return 29; break;
    case "Master Yi": return 11; break;
    case "Taric": return 44; break;
    case "Amumu": return 32; break;
    case "Gangplank": return 41; break;
    case "Trundle": return 48; break;
    case "Kassadin": return 38; break;
    case "Vel'Koz": return 161; break;
    case "Zyra": return 143; break;
    case "Nami": return 267; break;
    case "Jarvan IV": return 59; break;
    case "Ezreal": return 81; break;
    case "Sett";return 0;break;
    case "Aphelios";return 0;break;
    case "Senna";return 0;break;
    case "Qiyana";return 0;break;
    case "Yummi";return 0;break;
    case "Silas";return 0;break;
    case "Neeko";return 0;break;
    case "Pyke";return 0;break;
    case "Kai'sa";return 0;break;
    case "Zoe";return 0;break;
    case "Ornn";return 0;break;
    case "Kayn";return 0;break;
    case "Rakan";return 0;break;
    case "Xayah";return 0;break;
    case "Camille";return 0;break;
    }
}
?>
